// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChat(arg1) {
  return window['go']['usecase']['config']['AddChat'](arg1);
}

export function GetAnonymousUsername() {
  return window['go']['usecase']['config']['GetAnonymousUsername']();
}

export function GetChats() {
  return window['go']['usecase']['config']['GetChats']();
}

export function GetClientID() {
  return window['go']['usecase']['config']['GetClientID']();
}

export function GetConfig() {
  return window['go']['usecase']['config']['GetConfig']();
}

export function GetLang() {
  return window['go']['usecase']['config']['GetLang']();
}

export function GetTwitchToken() {
  return window['go']['usecase']['config']['GetTwitchToken']();
}

export function GetTwitchUserInfo() {
  return window['go']['usecase']['config']['GetTwitchUserInfo']();
}

export function RemoveChat(arg1) {
  return window['go']['usecase']['config']['RemoveChat'](arg1);
}

export function SaveAnonymousUsername(arg1) {
  return window['go']['usecase']['config']['SaveAnonymousUsername'](arg1);
}

export function SaveLang(arg1) {
  return window['go']['usecase']['config']['SaveLang'](arg1);
}

export function SaveTwitchInfo(arg1) {
  return window['go']['usecase']['config']['SaveTwitchInfo'](arg1);
}
