// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddChat(arg1:model.Chat):Promise<void>;

export function GetAnonymousUsername():Promise<string>;

export function GetChats():Promise<Array<model.Chat>>;

export function GetClientID():Promise<string>;

export function GetConfig():Promise<model.Config>;

export function GetLang():Promise<string>;

export function GetMuttedUsers():Promise<Array<string>>;

export function GetSampleRateOfTTS():Promise<number>;

export function GetTwitchToken():Promise<string>;

export function GetTwitchUserInfo():Promise<model.TwitchUser>;

export function IsMutted(arg1:string):Promise<boolean>;

export function RemoveChat(arg1:string):Promise<void>;

export function SaveAnonymousUsername(arg1:string):Promise<void>;

export function SaveLang(arg1:string):Promise<void>;

export function SaveTwitchInfo(arg1:model.TwitchInfo):Promise<void>;

export function ToggleMuttedUser(arg1:string):Promise<Array<string>>;
