// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {twitch} from '../models';

export function GetType():Promise<twitch.MessageType>;
