// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnonymousUsername() {
  return window['go']['repo']['repoConfigFile']['GetAnonymousUsername']();
}

export function GetClientID() {
  return window['go']['repo']['repoConfigFile']['GetClientID']();
}

export function GetConfig() {
  return window['go']['repo']['repoConfigFile']['GetConfig']();
}

export function GetLang() {
  return window['go']['repo']['repoConfigFile']['GetLang']();
}

export function GetTwitchToken() {
  return window['go']['repo']['repoConfigFile']['GetTwitchToken']();
}

export function SaveAnonymousUsername(arg1) {
  return window['go']['repo']['repoConfigFile']['SaveAnonymousUsername'](arg1);
}

export function SaveLang(arg1) {
  return window['go']['repo']['repoConfigFile']['SaveLang'](arg1);
}

export function SaveTwitchInfo(arg1) {
  return window['go']['repo']['repoConfigFile']['SaveTwitchInfo'](arg1);
}
