// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['tts']['TTS']['Add'](arg1);
}

export function Continue() {
  return window['go']['tts']['TTS']['Continue']();
}

export function Next() {
  return window['go']['tts']['TTS']['Next']();
}

export function OnPlayerEnds(arg1) {
  return window['go']['tts']['TTS']['OnPlayerEnds'](arg1);
}

export function OnPlayerStart(arg1) {
  return window['go']['tts']['TTS']['OnPlayerStart'](arg1);
}

export function Pause() {
  return window['go']['tts']['TTS']['Pause']();
}

export function Play() {
  return window['go']['tts']['TTS']['Play']();
}

export function Stop() {
  return window['go']['tts']['TTS']['Stop']();
}
