// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<void>;

export function Continue():Promise<void>;

export function Next():Promise<void>;

export function OnPlayerEnds(arg1:any):Promise<void>;

export function OnPlayerStart(arg1:any):Promise<void>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function Stop():Promise<void>;
