// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RestaUno():Promise<number>;

export function SumaUno():Promise<number>;
