// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RestaUno() {
  return window['go']['app']['Estado']['RestaUno']();
}

export function SumaUno() {
  return window['go']['app']['Estado']['SumaUno']();
}
