// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1) {
  return window['go']['app']['MainApp']['Run'](arg1);
}

export function Stop() {
  return window['go']['app']['MainApp']['Stop']();
}
