// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function IsLoggedIn():Promise<boolean>;

export function Run(arg1:fs.FS):Promise<Error>;

export function Stop():Promise<void>;
