// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {func(} from '../models';

export function EventsOn(arg1:context.Context,arg2:string,arg3:func(.):Promise<void>;

export function Tiempo():Promise<string>;
