// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Saludo(arg1:string):Promise<string>;

export function Suma(arg1:number,arg2:number):Promise<number>;

export function Tiempo():Promise<string>;
