// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Saludo(arg1) {
  return window['go']['main']['Prueba']['Saludo'](arg1);
}

export function Suma(arg1, arg2) {
  return window['go']['main']['Prueba']['Suma'](arg1, arg2);
}

export function Tiempo() {
  return window['go']['main']['Prueba']['Tiempo']();
}
