// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsOn(arg1, arg2, arg3) {
  return window['go']['main']['Prueba']['EventsOn'](arg1, arg2, arg3);
}

export function Tiempo() {
  return window['go']['main']['Prueba']['Tiempo']();
}
